os: linux
dist: focal
language: go
go:
  - 1.17.x
env:
  global:
    - CI_CONFIG_DIR=build/ci/.env
    - BRANCH_NAME=$TRAVIS_BRANCH
    - CI_STAGE=$TRAVIS_BUILD_STAGE_NAME

branches:
  only:
    - master
    - izajusi

script: bash build/ci/ci.sh $CI_STAGE $CMD_PATH $BRANCH_NAME

jobs:
  include:
    # BUILD BASE IMAGE
    - stage: "build-base"
      name: "base_image"
      if: type = push AND (commit_message =~ /\(build_base\)/ OR commit_message =~ /build_all/)

    # ADD YOUR SERVICE OR CONSOLE HERE
    - stage: "build"
      name: "app"
      env: CMD_PATH=cmd/app
      if: type = push AND (commit_message =~ /\(app\)/ OR commit_message =~ /build_all/)
